language: ruby
rvm:
  - 2.0.0
  - 1.9.3
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - "cd test/dummy; rake db:migrate; rake db:test:prepare; cd ../.."
notifications:
  email: false